theme: minima
title: DHTL Page for Posting
author: Jordan
email: 
description: > # this means to ignore newlines until "baseurl:"
  DHTL Fantasy League Official Blog

# social links
twitter_username:  # DO NOT include the @ character, or else the build will fail!
github_username:  jtskubic # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
